<?php

namespace App;

use function foo\func;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    public function question(){
        return $this->belongsTo(Question::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($answer){
            $answer->question->increment('answers_count');
            $answer->question->save();
        });

    }
}
